site_name: vireon-lab
site_description: Educational Platform & Interactive Laboratory for Neurosecurity
repo_url: https://github.com/SaadiMalik1/vireon-lab
repo_name: SaadiMalik1/vireon-lab

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: deep purple

plugins:
  - search

nav:
  - Overview: README.md
